// Generated by CoffeeScript 1.7.1
(function() {
  var request, should;

  should = require('should');

  request = require('supertest');

  describe('RestSevice', function() {
    before(function(done) {
      this.url = "http://localhost:8080";
      return done();
    });
    return describe('First level of beer styles and links', function() {
      var address;
      address = '/getData';
      return it('Should have a correctly structured json object', function(done) {
        return request(this.url).get(address).expect('Content-Type', /json/).expect(200).end(function(err, res) {
          var key, link, _i, _len, _ref, _results;
          if (err) {
            throw err;
          }
          Object.keys(res.body).length.should.not.equal(0);
          _ref = res.body;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            key = _ref[_i];
            key.should.be.type('number');
            res.body[key].name.should.be.type('string');
            res.body[key].superNode.should.be.type('boolean');
            res.body[key].type.should.be.type('string');
            Array.isArray(res.body[key].links).should.equal(true);
            _results.push((function() {
              var _j, _len1, _ref1, _results1;
              _ref1 = res.body[key].links;
              _results1 = [];
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                link = _ref1[_j];
                _results1.push(link.should.be.type('number'));
              }
              return _results1;
            })());
          }
          return _results;
        });
      });
    });
  });

}).call(this);
